# Generated by Django 4.2.6 on 2023-10-19 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_link_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="places",
                to="projects.project",
            ),
        ),
    ]
