# Generated by Django 4.2.6 on 2023-10-16 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_alter_project_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="due_date",
        ),
    ]
