# Generated by Django 4.2.6 on 2023-10-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_alter_place_project"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ("-status",)},
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Not Started"),
                    (2, "Impending"),
                    (3, "In Progress"),
                    (4, "Completed"),
                    (5, "Archived"),
                ],
                default=1,
            ),
        ),
    ]
