# Generated by Django 4.2.6 on 2023-11-07 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="checked",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="note",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="projects.project",
            ),
        ),
    ]
