version: '3.9'

services:
  web:
    build: ./
    command: python manage.py runserver_plus --settings=core.settings.development 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/organize_it/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
      image: postgres:16
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=hello_django
        - POSTGRES_PASSWORD=hello_django
        - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:
