# Generated by Django 6.0.6 on 2026-06-30 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import suggestions.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AICredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("gemini", "Google Gemini")],
                        default="gemini",
                        max_length=20,
                    ),
                ),
                ("api_key_encrypted", suggestions.fields.EncryptedTextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI credentials",
                "verbose_name_plural": "AI credentials",
            },
        ),
        migrations.CreateModel(
            name="SuggestionPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "favored_experience_types",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "dietary",
                    models.CharField(
                        choices=[
                            ("none", "No preference"),
                            ("vegetarian", "Vegetarian"),
                            ("vegan", "Vegan"),
                            ("gluten_free", "Gluten-free"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "pace",
                    models.CharField(
                        choices=[
                            ("relaxed", "Relaxed"),
                            ("moderate", "Moderate"),
                            ("packed", "Packed"),
                        ],
                        default="moderate",
                        max_length=20,
                    ),
                ),
                (
                    "budget",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestion_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Suggestion preferences",
                "verbose_name_plural": "Suggestion preferences",
            },
        ),
    ]
