# Generated by Django 6.0.6 on 2026-07-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suggestions", "0002_suggestionpreferences_result_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="suggestionpreferences",
            name="pace",
        ),
        migrations.AddField(
            model_name="suggestionpreferences",
            name="cuisine",
            field=models.CharField(
                choices=[
                    ("any", "No preference"),
                    ("local", "Local traditional"),
                    ("street_food", "Street food"),
                    ("international", "International"),
                ],
                default="any",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="suggestionpreferences",
            name="interests",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="suggestionpreferences",
            name="travel_party",
            field=models.CharField(
                choices=[
                    ("unspecified", "Not specified"),
                    ("solo", "Solo"),
                    ("couple", "Couple"),
                    ("family", "Family with children"),
                    ("friends", "Group of friends"),
                ],
                default="unspecified",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="suggestionpreferences",
            name="travel_style",
            field=models.CharField(
                choices=[
                    ("iconic", "Iconic must-sees"),
                    ("balanced", "Balanced"),
                    ("offbeat", "Off the beaten path"),
                ],
                default="balanced",
                max_length=20,
            ),
        ),
    ]
