# Generated by Django 6.0.6 on 2026-07-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suggestions", "0003_remove_suggestionpreferences_pace_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestionpreferences",
            name="search_radius",
            field=models.CharField(
                choices=[
                    ("city", "Within the city"),
                    ("nearby", "City and surroundings"),
                    ("day_trips", "Include day trips"),
                ],
                default="nearby",
                max_length=20,
            ),
        ),
    ]
