# Generated by Django 6.0.6 on 2026-07-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suggestions", "0004_suggestionpreferences_search_radius"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aicredentials",
            name="provider",
            field=models.CharField(
                choices=[("gemini", "Google Gemini"), ("mistral", "Mistral AI")],
                default="gemini",
                max_length=20,
            ),
        ),
    ]
