# Generated by Django 6.0.6 on 2026-07-07 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suggestions", "0005_alter_aicredentials_provider"),
        ("trips", "0042_remove_staytransfer_trips_stay__from_da_2475ff_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aicredentials",
            name="share_with_collaborators",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, collaborators of trips you created can use your key to generate AI suggestions if they have not configured their own.",
                verbose_name="Share API key with collaborators",
            ),
        ),
        migrations.CreateModel(
            name="SharedKeyNoticeDismissal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_key_notice_dismissals",
                        to="trips.trip",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_key_notice_dismissals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "trip"), name="unique_shared_key_dismissal"
                    )
                ],
            },
        ),
    ]
