# Generated by Django 6.0.1 on 2026-01-12 13:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="First name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Last name"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="City"
                    ),
                ),
                (
                    "avatar",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("passport.png", "Passport"),
                            ("camping.png", "Camping"),
                            ("car.png", "Car"),
                            ("desert.png", "Desert"),
                            ("hiker.png", "Hiker"),
                            ("scuba-diving.png", "Scuba Diving"),
                            ("tourist.png", "Tourist"),
                            ("traveller.png", "Traveller"),
                        ],
                        default="",
                        max_length=50,
                        verbose_name="Avatar",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EUR", "Euro (€)"),
                            ("USD", "US Dollar ($)"),
                            ("GBP", "Pound Sterling (£)"),
                        ],
                        default="EUR",
                        max_length=3,
                        verbose_name="Preferred currency",
                    ),
                ),
                (
                    "default_map_view",
                    models.CharField(
                        choices=[("list", "List"), ("map", "Map")],
                        default="list",
                        max_length=4,
                        verbose_name="Default map view",
                    ),
                ),
                (
                    "trip_sort_preference",
                    models.CharField(
                        choices=[
                            ("date_asc", "Date (oldest first)"),
                            ("date_desc", "Date (newest first)"),
                            ("name_asc", "Name (A-Z)"),
                            ("name_desc", "Name (Z-A)"),
                        ],
                        default="date_asc",
                        max_length=10,
                        verbose_name="Trip sorting",
                    ),
                ),
                (
                    "use_system_theme",
                    models.BooleanField(
                        default=False,
                        help_text="Follow your device's theme preference instead of manual selection",
                        verbose_name="Use system theme",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
    ]
