# Generated by Django 4.2.7 on 2023-11-22 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_note_checked_alter_note_project"),
        ("accounts", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="fav_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.project",
            ),
        ),
    ]
