# Generated by Django 6.0 on 2025-12-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="City"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="First name"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="Last name"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                upload_to="profile_pictures/",
                verbose_name="Profile picture",
            ),
        ),
    ]
