# Generated by Django 6.0.3 on 2026-03-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="home_address",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="Home address"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="home_address_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="home_address_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
