# Generated by Django 4.2.7 on 2023-11-23 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0009_alter_project_links"),
        ("accounts", "0003_alter_profile_fav_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="fav_project",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.project",
            ),
        ),
    ]
