# Generated by Django 6.0.3 on 2026-03-28 11:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0003_profile_home_address_profile_home_address_latitude_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="city",
        ),
    ]
