# Generated by Django 6.0 on 2025-12-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_profile_city_profile_first_name_profile_last_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.CharField(
                blank=True,
                choices=[
                    ("boarding-pass.png", "Boarding Pass"),
                    ("camping.png", "Camping"),
                    ("car.png", "Car"),
                    ("desert.png", "Desert"),
                    ("hiker.png", "Hiker"),
                    ("scuba-diving.png", "Scuba Diving"),
                    ("tourist.png", "Tourist"),
                    ("traveller.png", "Traveller"),
                ],
                default="",
                max_length=50,
                verbose_name="Avatar",
            ),
        ),
    ]
