# Generated by Django 6.0 on 2025-12-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_remove_profile_profile_picture_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EUR", "Euro (€)"),
                    ("USD", "US Dollar ($)"),
                    ("GBP", "Pound Sterling (£)"),
                ],
                default="EUR",
                max_length=3,
                verbose_name="Preferred currency",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.CharField(
                blank=True,
                choices=[
                    ("passport.png", "Passport"),
                    ("camping.png", "Camping"),
                    ("car.png", "Car"),
                    ("desert.png", "Desert"),
                    ("hiker.png", "Hiker"),
                    ("scuba-diving.png", "Scuba Diving"),
                    ("tourist.png", "Tourist"),
                    ("traveller.png", "Traveller"),
                ],
                default="",
                max_length=50,
                verbose_name="Avatar",
            ),
        ),
    ]
