# Generated by Django 6.0.3 on 2026-03-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_remove_profile_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="home_address",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Used to pre-fill the origin/destination field in car transfers. It is not shared or used for any other purpose.",
                max_length=500,
                verbose_name="Home address",
            ),
        ),
    ]
