# Generated by Django 6.0.3 on 2026-04-04 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_profile_home_address"),
        ("trips", "0013_event_last_modified_by_maintransfer_last_modified_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="fav_trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="trips.trip",
            ),
        ),
    ]
