# Generated by Django 6.0 on 2025-12-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_profile_currency_alter_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="default_map_view",
            field=models.CharField(
                blank=True,
                choices=[("list", "List"), ("map", "Map")],
                default="list",
                max_length=4,
                verbose_name="Default map view",
            ),
        ),
    ]
