# Generated by Django 6.0 on 2025-12-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_profile_default_map_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="trip_sort_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("status", "Status (default)"),
                    ("date_asc", "Date (oldest first)"),
                    ("date_desc", "Date (newest first)"),
                    ("name_asc", "Name (A-Z)"),
                    ("name_desc", "Name (Z-A)"),
                ],
                default="status",
                max_length=10,
                verbose_name="Trip sorting",
            ),
        ),
    ]
