# Generated by Django 6.0.3 on 2026-04-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_profile_fav_trip"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="language",
            field=models.CharField(
                choices=[("it", "Italian"), ("en", "English")],
                default="it",
                max_length=5,
                verbose_name="Language",
            ),
        ),
    ]
