# Generated by Django 6.0 on 2025-12-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_profile_trip_sort_preference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="trip_sort_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("date_asc", "Date (oldest first)"),
                    ("date_desc", "Date (newest first)"),
                    ("name_asc", "Name (A-Z)"),
                    ("name_desc", "Name (Z-A)"),
                ],
                default="date_asc",
                max_length=10,
                verbose_name="Trip sorting",
            ),
        ),
    ]
