# Generated by Django 6.0.5 on 2026-05-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_profile_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="show_transfer_info",
            field=models.BooleanField(
                default=True,
                help_text="Show duration and distance info between trip stages.",
                verbose_name="Show transfer info",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_weather",
            field=models.BooleanField(
                default=True,
                help_text="Show weather forecast on trip days. When disabled, weather data is not fetched from the API.",
                verbose_name="Show weather forecast",
            ),
        ),
    ]
