# Generated by Django 6.0.5 on 2026-05-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_add_show_transfer_info_show_weather_to_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="show_weather",
            field=models.BooleanField(
                default=True,
                help_text="When disabled, weather data is not fetched from the API.",
                verbose_name="Show weather forecast",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="use_system_theme",
            field=models.BooleanField(
                default=False,
                help_text="Use your device's light/dark system setting.",
                verbose_name="Use system theme",
            ),
        ),
    ]
