# Generated by Django 6.0.6 on 2026-06-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_profile_show_weather_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="notify_daily_digest",
            field=models.BooleanField(
                default=True,
                help_text="Receive a daily summary email of your trip plan during the trip.",
                verbose_name="Daily digest email",
            ),
        ),
    ]
