# Generated by Django 6.0 on 2025-12-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_profile_trip_sort_preference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="default_map_view",
            field=models.CharField(
                choices=[("list", "List"), ("map", "Map")],
                default="list",
                max_length=4,
                verbose_name="Default map view",
            ),
        ),
    ]
