# Generated by Django 6.0.6 on 2026-07-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_profile_notify_daily_digest"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="ai_suggestions_enabled",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, the AI suggestions settings and the in-app AI suggestions features become available.",
                verbose_name="Enable AI suggestions",
            ),
        ),
    ]
