# Generated by Django 6.0 on 2025-12-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_profile_theme"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="theme",
        ),
        migrations.AddField(
            model_name="profile",
            name="use_system_theme",
            field=models.BooleanField(
                default=False,
                help_text="Follow your device's theme preference instead of manual selection",
                verbose_name="Use system theme",
            ),
        ),
    ]
