# Generated by Django 6.0.1 on 2026-01-12 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
                ("date", models.DateField()),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("address", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "category",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Transport"), (2, "Experience"), (3, "Meal")],
                        default=2,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("place_id", models.CharField(blank=True, max_length=255)),
                ("website", models.URLField(blank=True, max_length=255)),
                ("phone_number", models.CharField(blank=True, max_length=50)),
                ("opening_hours", models.JSONField(blank=True, null=True)),
                ("enriched", models.BooleanField(default=False)),
                (
                    "day",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="trips.day",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="Stay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("check_in", models.TimeField(blank=True, null=True)),
                ("check_out", models.TimeField(blank=True, null=True)),
                ("cancellation_date", models.DateField(blank=True, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=50)),
                ("website", models.URLField(blank=True, max_length=255)),
                ("address", models.CharField(max_length=200)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("place_id", models.CharField(blank=True, max_length=255)),
                ("opening_hours", models.JSONField(blank=True, null=True)),
                ("enriched", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="trips.event",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Museum"),
                            (2, "Park"),
                            (3, "Walk"),
                            (4, "Sport"),
                            (5, "Other"),
                        ],
                        default=1,
                    ),
                ),
            ],
            bases=("trips.event",),
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="trips.event",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Breakfast"),
                            (2, "Lunch"),
                            (3, "Dinner"),
                            (4, "Snack"),
                        ],
                        default=2,
                    ),
                ),
            ],
            bases=("trips.event",),
        ),
        migrations.CreateModel(
            name="Transport",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="trips.event",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Car"),
                            (2, "Plane"),
                            (3, "Train"),
                            (4, "Boat"),
                            (5, "Bus"),
                            (6, "Taxi"),
                            (7, "Other"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "is_main_transfer",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if this is a main arrival/departure transfer",
                    ),
                ),
                (
                    "direction",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Arrival"), (2, "Departure")],
                        help_text="Required for main transfers (arrival or departure)",
                        null=True,
                    ),
                ),
                (
                    "type_specific_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Type-specific fields: flight_number, train_number, rental_info, etc.",
                    ),
                ),
                ("origin_city", models.CharField(max_length=100)),
                ("origin_address", models.CharField(blank=True, max_length=200)),
                ("origin_latitude", models.FloatField(blank=True, null=True)),
                ("origin_longitude", models.FloatField(blank=True, null=True)),
                ("destination_city", models.CharField(max_length=100)),
                ("destination_address", models.CharField(blank=True, max_length=200)),
                ("destination_latitude", models.FloatField(blank=True, null=True)),
                ("destination_longitude", models.FloatField(blank=True, null=True)),
                ("booking_reference", models.CharField(blank=True, max_length=100)),
                ("company", models.CharField(blank=True, max_length=100)),
                ("ticket_url", models.URLField(blank=True, max_length=255)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            bases=("trips.event",),
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("url", models.URLField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="day",
            name="stay",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="days",
                to="trips.stay",
            ),
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("destination", models.CharField(max_length=100)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Not started"),
                            (2, "Impending"),
                            (3, "In progress"),
                            (4, "Completed"),
                            (5, "Archived"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Trip cover image (landscape, max 2MB)",
                        null=True,
                        upload_to="trips/%Y/%m/",
                    ),
                ),
                (
                    "image_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Image source and attribution data",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "links",
                    models.ManyToManyField(
                        blank=True, related_name="trips", to="trips.link"
                    ),
                ),
            ],
            options={
                "ordering": ("status",),
            },
        ),
        migrations.AddField(
            model_name="event",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="all_events",
                to="trips.trip",
            ),
        ),
        migrations.AddField(
            model_name="day",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days",
                to="trips.trip",
            ),
        ),
        migrations.CreateModel(
            name="MainTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "Plane"), (2, "Train"), (3, "Car"), (4, "Other")],
                        help_text="Type of transport (plane, train, car, other)",
                    ),
                ),
                (
                    "direction",
                    models.IntegerField(
                        choices=[(1, "Arrival"), (2, "Departure")],
                        help_text="Arrival (to destination) or Departure (from destination)",
                    ),
                ),
                (
                    "origin_code",
                    models.CharField(
                        blank=True,
                        help_text="IATA code (plane) or station ID (train)",
                        max_length=10,
                    ),
                ),
                (
                    "origin_name",
                    models.CharField(help_text="Airport/station name", max_length=200),
                ),
                (
                    "destination_code",
                    models.CharField(
                        blank=True,
                        help_text="IATA code (plane) or station ID (train)",
                        max_length=10,
                    ),
                ),
                (
                    "destination_name",
                    models.CharField(help_text="Airport/station name", max_length=200),
                ),
                (
                    "origin_address",
                    models.CharField(
                        blank=True,
                        help_text="Full address for car/other transport",
                        max_length=500,
                    ),
                ),
                (
                    "destination_address",
                    models.CharField(
                        blank=True,
                        help_text="Full address for car/other transport",
                        max_length=500,
                    ),
                ),
                ("origin_latitude", models.FloatField(blank=True, null=True)),
                ("origin_longitude", models.FloatField(blank=True, null=True)),
                ("destination_latitude", models.FloatField(blank=True, null=True)),
                ("destination_longitude", models.FloatField(blank=True, null=True)),
                ("start_time", models.TimeField(help_text="Departure time")),
                ("end_time", models.TimeField(help_text="Arrival time")),
                (
                    "booking_reference",
                    models.CharField(
                        blank=True,
                        help_text="Booking/reservation reference",
                        max_length=100,
                    ),
                ),
                (
                    "ticket_url",
                    models.URLField(blank=True, help_text="Link to ticket or booking"),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "type_specific_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Type-specific fields: company, flight_number, train_number, etc.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_transfers",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Main Transfer",
                "verbose_name_plural": "Main Transfers",
                "db_table": "trips_main_transfer",
                "ordering": ["direction", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["trip", "direction"],
                        name="trips_main__trip_id_c8629e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("trip", "direction"),
                        name="unique_trip_maintransfer_direction",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["day_id", "start_time"], name="trips_event_day_id_7669b5_idx"
            ),
        ),
    ]
