# Generated by Django 5.2.7 on 2025-11-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Trip cover image (landscape, max 2MB)",
                null=True,
                upload_to="trips/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="image_metadata",
            field=models.JSONField(
                blank=True, default=dict, help_text="Image source and attribution data"
            ),
        ),
    ]
