# Generated by Django 4.2.7 on 2023-11-28 07:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="project",
            new_name="trip",
        ),
        migrations.RenameField(
            model_name="place",
            old_name="project",
            new_name="trip",
        ),
    ]
