# Generated by Django 5.2 on 2025-04-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Not started"),
                    (2, "Impending"),
                    (3, "In progress"),
                    (4, "Completed"),
                    (5, "Archived"),
                ],
                default=1,
            ),
        ),
    ]
