# Generated by Django 5.1.6 on 2025-02-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="order",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
