# Generated by Django 5.1.6 on 2025-02-18 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Plane"),
                            (2, "Train"),
                            (3, "Boat"),
                            (4, "Bus"),
                            (5, "Taxi"),
                            (6, "Other"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transports",
                        to="trips.day",
                    ),
                ),
            ],
        ),
    ]
