# Generated by Django 6.0.1 on 2026-01-12 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimpleTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transport_mode",
                    models.CharField(
                        choices=[
                            ("car", "Car"),
                            ("train", "Train"),
                            ("plane", "Plane"),
                            ("walk", "Walk"),
                            ("bus", "Bus"),
                            ("boat", "Boat"),
                            ("taxi", "Taxi"),
                            ("other", "Other"),
                        ],
                        default="car",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("departure_time", models.TimeField(blank=True, null=True)),
                ("estimated_duration", models.DurationField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simple_transfers",
                        to="trips.day",
                    ),
                ),
                (
                    "from_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_from",
                        to="trips.event",
                    ),
                ),
                (
                    "to_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_to",
                        to="trips.event",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simple_transfers",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Simple Transfer",
                "verbose_name_plural": "Simple Transfers",
                "db_table": "trips_simple_transfer",
                "ordering": ["day__number", "from_event__start_time"],
                "indexes": [
                    models.Index(
                        fields=["day", "from_event"],
                        name="trips_simpl_day_id_a477c6_idx",
                    ),
                    models.Index(
                        fields=["trip"], name="trips_simpl_trip_id_e9278e_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("from_event", models.F("to_event")), _negated=True
                        ),
                        name="simple_transfer_different_events",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StayTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transport_mode",
                    models.CharField(
                        choices=[
                            ("car", "Car"),
                            ("train", "Train"),
                            ("plane", "Plane"),
                            ("walk", "Walk"),
                            ("bus", "Bus"),
                            ("boat", "Boat"),
                            ("taxi", "Taxi"),
                            ("other", "Other"),
                        ],
                        default="car",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("departure_time", models.TimeField(blank=True, null=True)),
                ("estimated_duration", models.DurationField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stay_transfers_from",
                        to="trips.day",
                    ),
                ),
                (
                    "from_stay",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_from",
                        to="trips.stay",
                    ),
                ),
                (
                    "to_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stay_transfers_to",
                        to="trips.day",
                    ),
                ),
                (
                    "to_stay",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_to",
                        to="trips.stay",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stay_transfers",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stay Transfer",
                "verbose_name_plural": "Stay Transfers",
                "db_table": "trips_stay_transfer",
                "ordering": ["from_day__number"],
                "indexes": [
                    models.Index(
                        fields=["from_day", "to_day"],
                        name="trips_stay__from_da_2475ff_idx",
                    ),
                    models.Index(
                        fields=["trip"], name="trips_stay__trip_id_532158_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("from_stay", models.F("to_stay")), _negated=True
                        ),
                        name="stay_transfer_different_stays",
                    )
                ],
            },
        ),
    ]
