# Generated by Django 5.2 on 2025-05-06 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0002_alter_trip_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="link",
        ),
        migrations.RemoveField(
            model_name="note",
            name="trip",
        ),
        migrations.AddField(
            model_name="note",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notes",
                to="trips.event",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="stay",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notes",
                to="trips.stay",
            ),
        ),
    ]
