# Generated by Django 4.2.7 on 2023-11-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0002_rename_project_note_trip_rename_project_place_trip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="links",
            field=models.ManyToManyField(
                blank=True, related_name="trips", to="trips.link"
            ),
        ),
    ]
