# Generated by Django 5.1.6 on 2025-02-19 13:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0002_transport"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transport",
            old_name="start",
            new_name="departure",
        ),
    ]
