# Generated by Django 5.1.6 on 2025-02-23 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0002_alter_event_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="trips.day",
            ),
        ),
    ]
