# Generated by Django 5.2.1 on 2025-05-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0002_alter_trip_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="description",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
