# Generated by Django 6.0 on 2025-12-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0002_trip_image_trip_image_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="transport",
            name="direction",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Arrival"), (2, "Departure")],
                help_text="Required for main transfers (arrival or departure)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transport",
            name="is_main_transfer",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True if this is a main arrival/departure transfer",
            ),
        ),
        migrations.AddField(
            model_name="transport",
            name="type_specific_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Type-specific fields: flight_number, train_number, rental_info, etc.",
            ),
        ),
        migrations.AddConstraint(
            model_name="transport",
            constraint=models.UniqueConstraint(
                condition=models.Q(is_main_transfer=True),
                fields=("trip", "direction"),
                name="unique_main_transfer_per_direction",
            ),
        ),
    ]
