# Generated by Django 5.1.6 on 2025-02-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0003_alter_event_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Transport"), (2, "Experience"), (3, "Meal"), (4, "Stay")],
                default=2,
            ),
        ),
    ]
