# Generated by Django 6.0.1 on 2026-01-16 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0003_alter_simpletransfer_transport_mode_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simpletransfer",
            name="departure_time",
        ),
        migrations.RemoveField(
            model_name="simpletransfer",
            name="estimated_duration",
        ),
    ]
