# Generated by Django 5.2.1 on 2025-05-09 08:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0003_alter_trip_description"),
        ("trips", "0003_remove_note_link_remove_note_trip_note_event_and_more"),
    ]

    operations = []
