# Generated by Django 6.0 on 2025-12-31 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0003_transport_direction_transport_is_main_transfer_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="transport",
            name="unique_main_transfer_per_direction",
        ),
        migrations.AlterField(
            model_name="event",
            name="address",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="event",
            name="day",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="trips.day",
            ),
        ),
        migrations.AddConstraint(
            model_name="transport",
            constraint=models.UniqueConstraint(
                condition=models.Q(is_main_transfer=True),
                fields=("trip", "direction"),
                name="unique_main_transfer_per_direction",
            ),
        ),
    ]
