# Generated by Django 5.2.1 on 2025-05-11 11:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0004_merge_20250509_1045"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="day",
            options={"ordering": ["number"]},
        ),
    ]
