# Generated by Django 5.1.6 on 2025-02-23 08:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0004_event_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["order"]},
        ),
    ]
