# Generated by Django 4.2.7 on 2023-12-02 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0004_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="day",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="places",
                to="trips.day",
            ),
        ),
    ]
