# Generated by Django 6.0 on 2026-01-03 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0004_remove_transport_unique_main_transfer_per_direction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "Plane"), (2, "Train"), (3, "Car"), (4, "Other")],
                        help_text="Type of transport (plane, train, car, other)",
                    ),
                ),
                (
                    "direction",
                    models.IntegerField(
                        choices=[(1, "Arrival"), (2, "Departure")],
                        help_text="Arrival (to destination) or Departure (from destination)",
                    ),
                ),
                (
                    "origin_code",
                    models.CharField(
                        blank=True,
                        help_text="IATA code (plane) or station ID (train)",
                        max_length=10,
                    ),
                ),
                (
                    "origin_name",
                    models.CharField(help_text="Airport/station name", max_length=200),
                ),
                (
                    "destination_code",
                    models.CharField(
                        blank=True,
                        help_text="IATA code (plane) or station ID (train)",
                        max_length=10,
                    ),
                ),
                (
                    "destination_name",
                    models.CharField(help_text="Airport/station name", max_length=200),
                ),
                (
                    "origin_address",
                    models.CharField(
                        blank=True,
                        help_text="Full address for car/other transport",
                        max_length=500,
                    ),
                ),
                (
                    "destination_address",
                    models.CharField(
                        blank=True,
                        help_text="Full address for car/other transport",
                        max_length=500,
                    ),
                ),
                ("origin_latitude", models.FloatField(blank=True, null=True)),
                ("origin_longitude", models.FloatField(blank=True, null=True)),
                ("destination_latitude", models.FloatField(blank=True, null=True)),
                ("destination_longitude", models.FloatField(blank=True, null=True)),
                ("start_time", models.TimeField(help_text="Departure time")),
                ("end_time", models.TimeField(help_text="Arrival time")),
                (
                    "booking_reference",
                    models.CharField(
                        blank=True,
                        help_text="Booking/reservation reference",
                        max_length=100,
                    ),
                ),
                (
                    "ticket_url",
                    models.URLField(blank=True, help_text="Link to ticket or booking"),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "type_specific_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Type-specific fields: company, flight_number, train_number, etc.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_transfers",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Main Transfer",
                "verbose_name_plural": "Main Transfers",
                "db_table": "trips_main_transfer",
                "ordering": ["direction", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["trip", "direction"],
                        name="trips_main__trip_id_c8629e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("trip", "direction"),
                        name="unique_trip_maintransfer_direction",
                    )
                ],
            },
        ),
    ]
