# Generated by Django 6.0.1 on 2026-01-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0004_remove_simpletransfer_time_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.PositiveSmallIntegerField(
                choices=[(2, "Experience"), (3, "Meal")], default=2
            ),
        ),
        migrations.DeleteModel(
            name="Transport",
        ),
    ]
