# Generated by Django 5.1.6 on 2025-02-23 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0005_alter_event_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="trips.event",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Museum"),
                            (2, "Park"),
                            (3, "Walk"),
                            (4, "Sport"),
                            (6, "Other"),
                        ],
                        default=1,
                    ),
                ),
            ],
            bases=("trips.event",),
        ),
    ]
