# Generated by Django 6.0.1 on 2026-01-25 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0005_remove_transport_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainTransferConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transport_mode",
                    models.CharField(
                        choices=[
                            ("driving", "Driving"),
                            ("walking", "Walking"),
                            ("bicycling", "Bicycling"),
                            ("transit", "Transit"),
                        ],
                        default="driving",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="trips.event",
                    ),
                ),
                (
                    "main_transfer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connection",
                        to="trips.maintransfer",
                    ),
                ),
                (
                    "stay",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="trips.stay",
                    ),
                ),
            ],
            options={
                "verbose_name": "Main Transfer Connection",
                "verbose_name_plural": "Main Transfer Connections",
                "db_table": "trips_main_transfer_connection",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("event__isnull", False), ("stay__isnull", True)),
                            models.Q(("event__isnull", True), ("stay__isnull", False)),
                            _connector="OR",
                        ),
                        name="main_transfer_connection_one_destination",
                    )
                ],
            },
        ),
    ]
