# Generated by Django 5.2.1 on 2025-05-12 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0005_alter_day_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="checked",
        ),
        migrations.AlterField(
            model_name="note",
            name="event",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="note",
                to="trips.event",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="stay",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="note",
                to="trips.stay",
            ),
        ),
    ]
