# Generated by Django 6.0 on 2026-01-03 13:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0005_maintransfer"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="transport",
            name="unique_main_transfer_per_direction",
        ),
    ]
