# Generated by Django 5.2.1 on 2025-05-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0006_remove_note_checked_alter_note_event_alter_note_stay"),
    ]

    operations = [
        migrations.AddField(
            model_name="stay",
            name="notes",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
