# Generated by Django 6.0.3 on 2026-03-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0008_add_sharelink_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="weather_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="day",
            name="weather_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
