# Generated by Django 5.2.6 on 2025-09-16 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0008_event_notes_delete_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stay",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid phone number (with or without international prefix, and at most 2 spaces).",
                        regex="^\\+?\\d(?: ?\\d){7,19}$",
                    ),
                    django.core.validators.RegexValidator(
                        message="Phone number can contain at most 2 spaces.",
                        regex="^(?:[^ ]* ?){0,3}$|^\\+?\\d(?: ?\\d){7,19}$",
                    ),
                ],
            ),
        ),
    ]
