# Generated by Django 5.1.6 on 2025-02-24 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0009_remove_stay_days_day_stay"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["start_time"]},
        ),
    ]
