# Generated by Django 5.2.6 on 2025-09-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0009_alter_stay_phone_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stay",
            old_name="url",
            new_name="website",
        ),
        migrations.RemoveField(
            model_name="event",
            name="url",
        ),
        migrations.AddField(
            model_name="event",
            name="opening_hours",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="phone_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="event",
            name="place_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="event",
            name="website",
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
