# Generated by Django 5.2.7 on 2025-10-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0010_rename_url_stay_website_remove_event_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stay",
            name="city",
            field=models.CharField(default="Firenze", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="experience",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "Museum"),
                    (2, "Park"),
                    (3, "Walk"),
                    (4, "Sport"),
                    (5, "Other"),
                ],
                default=1,
            ),
        ),
    ]
