# Generated by Django 5.1.6 on 2025-02-24 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0010_alter_event_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="order",
        ),
    ]
