# Generated by Django 6.0.3 on 2026-03-27 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0010_schedule_fetch_weather"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maintransfer",
            name="booking_reference",
        ),
        migrations.RemoveField(
            model_name="maintransfer",
            name="ticket_url",
        ),
    ]
