# Generated by Django 5.1.6 on 2025-02-26 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0011_remove_event_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="day",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="day",
            name="location",
        ),
        migrations.RemoveField(
            model_name="day",
            name="longitude",
        ),
    ]
