# Generated by Django 5.2.7 on 2025-10-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0011_stay_city_alter_experience_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="stay",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
