# Generated by Django 6.0.3 on 2026-03-30 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0011_remove_maintransfer_booking_reference_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="day",
            index=models.Index(
                fields=["trip", "date"], name="trips_day_trip_id_05f6eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["trip_id"], name="trips_event_trip_id_a63d30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stay",
            index=models.Index(
                fields=["place_id"], name="trips_stay_place_i_c96203_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["author", "status"], name="trips_trip_author__4e2633_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["author", "-start_date"], name="trips_trip_author__dee8b4_idx"
            ),
        ),
    ]
