# Generated by Django 5.2.7 on 2025-10-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0012_event_city_alter_stay_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="enriched",
            field=models.BooleanField(default=False),
        ),
    ]
