# Generated by Django 5.1.6 on 2025-03-06 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0012_remove_day_latitude_remove_day_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="place",
        ),
        migrations.AlterField(
            model_name="day",
            name="stay",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="days",
                to="trips.stay",
            ),
        ),
        migrations.DeleteModel(
            name="Place",
        ),
    ]
