# Generated by Django 6.0.4 on 2026-04-23 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0013_event_last_modified_by_maintransfer_last_modified_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="description",
        ),
    ]
