# Generated by Django 5.2.7 on 2025-10-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0013_event_enriched"),
    ]

    operations = [
        migrations.AddField(
            model_name="stay",
            name="enriched",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stay",
            name="opening_hours",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stay",
            name="place_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="stay",
            name="phone_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="stay",
            name="website",
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
