# Generated by Django 6.0.4 on 2026-04-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0014_remove_trip_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["order", "pk"]},
        ),
        migrations.AlterModelOptions(
            name="simpletransfer",
            options={
                "ordering": ["day__number", "from_event__order"],
                "verbose_name": "Simple Transfer",
                "verbose_name_plural": "Simple Transfers",
            },
        ),
        migrations.RemoveIndex(
            model_name="event",
            name="trips_event_day_id_7669b5_idx",
        ),
        migrations.AddField(
            model_name="event",
            name="estimated_duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RemoveField(
            model_name="event",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="event",
            name="start_time",
        ),
    ]
