# Generated by Django 5.1.7 on 2025-03-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0014_alter_event_category"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["day_id", "start_time"], name="trips_event_day_id_7669b5_idx"
            ),
        ),
    ]
