# Generated by Django 5.1.7 on 2025-03-24 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0015_event_trips_event_day_id_7669b5_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="day",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="trips.day",
            ),
        ),
    ]
