# Generated by Django 6.0.4 on 2026-04-30 05:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0015_event_estimated_duration_order"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="simpletransfer",
            name="trips_simpl_day_id_a477c6_idx",
        ),
        migrations.RemoveIndex(
            model_name="simpletransfer",
            name="trips_simpl_trip_id_e9278e_idx",
        ),
        migrations.RemoveConstraint(
            model_name="simpletransfer",
            name="simple_transfer_different_events",
        ),
        migrations.DeleteModel(
            name="SimpleTransfer",
        ),
    ]
