# Generated by Django 6.0.4 on 2026-05-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0016_remove_simpletransfer"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripcollaboration",
            name="can_edit",
            field=models.BooleanField(default=True),
        ),
    ]
