# Generated by Django 6.0.4 on 2026-05-02 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0017_tripcollaboration_can_edit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tripcollaboration",
            name="participant_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="tripcollaboration",
            name="participant_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="tripcollaboration",
            name="share_link",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collaboration",
                to="trips.sharelink",
            ),
        ),
        migrations.AlterField(
            model_name="tripcollaboration",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trip_collaborations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
