# Generated by Django 6.0.4 on 2026-05-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0018_tripcollaboration_participant_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
