# Generated by Django 6.0.4 on 2026-05-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0019_event_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="type",
            field=models.IntegerField(
                choices=[
                    (0, "To be defined"),
                    (1, "Breakfast"),
                    (2, "Lunch"),
                    (3, "Dinner"),
                    (4, "Snack"),
                ],
                default=0,
            ),
        ),
    ]
