# Generated by Django 6.0.4 on 2026-05-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0020_alter_meal_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="destination",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="day",
            name="destination_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="day",
            name="destination_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="day",
            name="transfer_distance_to_next",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="day",
            name="transfer_duration_to_next",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
