# Generated by Django 6.0.4 on 2026-05-07 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0021_day_destination_day_destination_latitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="day",
            name="destination_latitude",
        ),
        migrations.RemoveField(
            model_name="day",
            name="destination_longitude",
        ),
    ]
