# Generated by Django 6.0.4 on 2026-05-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0022_remove_day_destination_coords"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="destination_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="day",
            name="destination_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
