# Generated by Django 6.0.4 on 2026-05-09 06:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0023_day_destination_latitude_day_destination_longitude"),
    ]

    operations = [
        migrations.RenameField(
            model_name="day",
            old_name="transfer_distance_to_next",
            new_name="transfer_distance_from_prev",
        ),
        migrations.RenameField(
            model_name="day",
            old_name="transfer_duration_to_next",
            new_name="transfer_duration_from_prev",
        ),
    ]
