# Generated by Django 6.0.4 on 2026-05-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "trips",
            "0024_rename_transfer_distance_to_next_day_transfer_distance_from_prev_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="enriched",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="stay",
            name="enriched",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
