# Generated by Django 6.0.4 on 2026-05-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0025_alter_event_enriched_alter_stay_enriched"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="stay",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
