# Generated by Django 6.0.5 on 2026-05-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0026_alter_event_notes_alter_stay_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="tag",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
