# Generated by Django 6.0.5 on 2026-05-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0027_add_tag_to_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="transfer_to_home_distance",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="day",
            name="transfer_to_home_duration",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
