# Generated by Django 6.0.5 on 2026-05-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0028_day_transfer_to_home_distance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="destination_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="destination_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
