# Generated by Django 6.0.5 on 2026-05-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0029_trip_destination_latitude_trip_destination_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintransfer",
            name="end_time",
            field=models.TimeField(blank=True, help_text="Arrival time", null=True),
        ),
        migrations.AlterField(
            model_name="maintransfer",
            name="start_time",
            field=models.TimeField(blank=True, help_text="Departure time", null=True),
        ),
    ]
