# Generated by Django 6.0.6 on 2026-06-06 06:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0032_schedule_checklist_reminders"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["day_id", "order"], name="trips_event_day_id_5ccbcc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["city"], name="trips_event_city_1eb74f_idx"),
        ),
    ]
