# Generated by Django 6.0.6 on 2026-06-07 08:35

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0033_event_trips_event_day_id_5ccbcc_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="calendar_token",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True
            ),
        ),
    ]
