# Generated by Django 6.0.6 on 2026-06-07 08:36

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    Trip = apps.get_model("trips", "Trip")
    for row in Trip.objects.all():
        row.calendar_token = uuid.uuid4()
        row.save(update_fields=["calendar_token"])


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0034_trip_calendar_token"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
