# Generated by Django 6.0.6 on 2026-06-07 08:36

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0035_populate_calendar_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="calendar_token",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True, unique=True
            ),
        ),
    ]
