# Generated by Django 6.0.6 on 2026-06-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0036_alter_trip_calendar_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="weather_reminder_sent_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
