# Generated by Django 6.0.6 on 2026-06-07 09:06

from django.db import migrations


def create_schedule(apps, schema_editor):
    Schedule = apps.get_model("django_q", "Schedule")
    db_alias = schema_editor.connection.alias
    Schedule.objects.using(db_alias).get_or_create(
        func="trips.tasks.send_weather_reminders",
        defaults={
            "name": "Send Weather Reminders",
            "func": "trips.tasks.send_weather_reminders",
            "schedule_type": "C",
            "cron": "0 9 * * *",
            "repeats": -1,
        },
    )


def delete_schedule(apps, schema_editor):
    Schedule = apps.get_model("django_q", "Schedule")
    db_alias = schema_editor.connection.alias
    Schedule.objects.using(db_alias).filter(
        func="trips.tasks.send_weather_reminders"
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0037_trip_weather_reminder_sent_at"),
    ]

    operations = [
        migrations.RunPython(create_schedule, delete_schedule),
    ]
