# Generated by Django 6.0.6 on 2026-06-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0039_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="daily_digest_sent_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
