# Generated by Django 6.0.6 on 2026-06-23 06:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0041_schedule_daily_digests"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="staytransfer",
            name="trips_stay__from_da_2475ff_idx",
        ),
        migrations.RemoveIndex(
            model_name="staytransfer",
            name="trips_stay__trip_id_532158_idx",
        ),
        migrations.RemoveConstraint(
            model_name="staytransfer",
            name="stay_transfer_different_stays",
        ),
        migrations.DeleteModel(
            name="StayTransfer",
        ),
    ]
