# Generated by Django 6.0.7 on 2026-07-19 17:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0043_trip_expense_currency_trip_expenses_enabled_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="category",
        ),
    ]
