# Generated by Django 6.0.7 on 2026-07-25 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0044_remove_expense_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripcollaboration",
            name="age",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(17)],
            ),
        ),
        migrations.AddField(
            model_name="tripcollaboration",
            name="is_child",
            field=models.BooleanField(default=False),
        ),
    ]
