# Generated by Django 6.0.7 on 2026-07-26 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0045_tripcollaboration_age_tripcollaboration_is_child"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StayBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination", models.CharField(max_length=100)),
                ("includes_author", models.BooleanField(default=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("smart", "Smart"),
                            ("booking", "Booking.com"),
                            ("expedia", "Expedia"),
                        ],
                        default="smart",
                        max_length=20,
                    ),
                ),
                ("hotel_name", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stay_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="stay_bookings",
                        to="trips.tripcollaboration",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "unique_together": {("trip", "destination", "created_by")},
            },
        ),
    ]
