# Generated by Django 6.0.7 on 2026-07-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0046_staybooking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staybooking",
            name="provider",
            field=models.CharField(
                choices=[
                    ("smart", "Best Deal (Smart)"),
                    ("booking", "Booking.com"),
                    ("expedia", "Expedia"),
                    ("hotelscom", "Hotels.com"),
                    ("airbnb", "Airbnb"),
                ],
                default="smart",
                max_length=20,
            ),
        ),
    ]
