# Generated by Django 6.0.7 on 2026-08-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0048_schedule_failure_hook"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="wizard_completed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="wizard_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="wizard_step",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
