# Generated by Django 6.0.8 on 2026-08-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0050_schedule_wizard_cleanup"),
    ]

    operations = [
        migrations.AddField(
            model_name="stay",
            name="board",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "No meals included"),
                    ("breakfast", "Breakfast included"),
                    ("half_board", "Half board"),
                    ("full_board", "Full board"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
