name: Tests Runner
on:
  push:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-22.04
    env:
      ALLOWED_HOSTS: '*'
      DEBUG: on
      SECRET_KEY: a secret to everybody
      MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
      TZ: UTC  # Set timezone to UTC
      PYTHONUNBUFFERED: 1

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test_db
        ports:
        - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Get the code
      uses: actions/checkout@v3

    - name: Install uv with cache enabled
      uses: astral-sh/setup-uv@v2
      with:
        enable-cache: true
        cache-dependency-glob: uv.lock

    - name: Set up Python
      run: uv python install

    - name: Install Python packages
      run: uv sync --all-extras --dev

    - name: Test it
      run: |
        # Run migrations before tests
        uv run python manage.py migrate --noinput
        # Run tests with -v 2 for more verbosity
        uv run pytest --reuse-db -v 2 -s
