name: Tests Runner
on:
  push:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-22.04
    env:
      ALLOWED_HOSTS: '*'
      DEBUG: on
      SECRET_KEY: a secret to everybody
      MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}

    steps:
    - name: Get the code
      uses: actions/checkout@v3

    - name: Install uv with cache enabled
      uses: astral-sh/setup-uv@v2
      with:
        enable-cache: true
        cache-dependency-glob: uv.lock

    - name: Set up Python
      run: uv python install

    - name: Install Python packages
      run: uv sync --all-extras --dev

    - name: Test it
      run: uv run COVERAGE_CORE=sysmon python -m pytest --reuse-db -s
